Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine314"
  config.vm.network "private_network", ip: "192.168.50.95"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 2375, host: 2375
  config.vm.provision "shell", path: "provisioner.sh"
end
